import {extractWorkspacePackages, isApplicationPackage, findWorkspaceRoot} from '../workspace'

/**
 * Generate systemd service file for a package
 */
async function generateServiceFile(packageName: string, domain: string, port: number): Promise<string> {
    const workingDir = `/home/garage44/garage44/packages/${packageName}`

    // Nonlinear needs WEBHOOK_SECRET for GitHub webhook handling
    const webhookSecretEnv = packageName === 'nonlinear' ?
        'Environment="WEBHOOK_SECRET=your-webhook-secret-here"\n' :
        ''

    return `[Unit]
Description=${packageName} service
After=network.target

[Service]
Type=simple
User=garage44
Group=garage44
WorkingDirectory=${workingDir}
Environment="NODE_ENV=production"
Environment="BUN_ENV=production"
${webhookSecretEnv}Environment="PATH=/home/garage44/.bun/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ExecStart=/home/garage44/.bun/bin/bun service.ts start --port ${port}
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
`
}

/**
 * Generate systemd service files for all packages
 */
export async function generateSystemd(domain: string): Promise<string> {
    const workspaceRoot = findWorkspaceRoot() || process.cwd()
    const packages = extractWorkspacePackages(workspaceRoot)
    const appPackages = packages.filter((pkg) => isApplicationPackage(pkg))

    // Port assignments
    const ports: Record<string, number> = {
        expressio: 3030,
        nonlinear: 3032,
        pyrite: 3031,
    }

    let output = `# Systemd service files for ${domain}\n`
    output += `# Generated by nonlinear generate-systemd --domain ${domain}\n\n`

    // Generate nonlinear service (main domain)
    output += `# Nonlinear service (main domain: ${domain})\n`
    output += await generateServiceFile('nonlinear', domain, ports['nonlinear'])
    output += '\n'

    // Generate services for application packages
    for (const pkg of appPackages) {
        const port = ports[pkg] || 3030 + appPackages.indexOf(pkg)
        output += `# ${pkg} service (subdomain: ${pkg}.${domain})\n`
        output += await generateServiceFile(pkg, domain, port)
        output += '\n'
    }

    return output
}
